#!/usr/bin/env python3
from signal import signal, SIG_IGN, SIGTERM, SIGINT
import subprocess
import sys
import os.path

USAGE = '''Usage: minecraftd [server jar path] [java options]*'''
JAVA_BIN = '/usr/bin/java'
JAVA_OPTS = []


def printf(fmt, *args):
    sys.stdout.write(fmt % tuple(args))
    sys.stdout.flush()


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(USAGE)
        exit(1)
    jar_path = sys.argv[1]
    opts = JAVA_OPTS + sys.argv[2:]
    args = [JAVA_BIN, '-server'] + opts + ['-jar', jar_path, 'nogui']

    if not os.path.exists("eula.txt"):
        with open("eula.txt", "w") as file:
            file.write("eula=true")

    if not os.path.exists(jar_path):
        from os import symlink
        symlink("../{}".format(jar_path), jar_path)

    printf('minecraftd: %s\n', ' '.join(args))

    def preexec():
        signal(SIGTERM, SIG_IGN)
        signal(SIGINT, SIG_IGN)

    p = subprocess.Popen(args=args, stdin=subprocess.PIPE,
                         preexec_fn=preexec)

    def handler(sig, _):
        printf('minecraftd: stopping server\n')
        p.stdin.write(b'stop\n')
        p.stdin.flush()

    signal(SIGTERM, handler)
    signal(SIGINT, handler)
    p.wait()
    printf('minecraftd: exit code is %d', p.returncode)
    sys.exit(p.returncode)